"""empty message

Revision ID: 810ce23aeb2f
Revises: e43337bff928
Create Date: 2022-03-30 14:27:31.871507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810ce23aeb2f'
down_revision = 'e43337bff928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=225), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=225), nullable=False),
    sa.Column('sigla', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=225), nullable=False),
    sa.Column('ibge', sa.String(length=10), nullable=False),
    sa.Column('uf_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uf_id'], ['uf.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disciplina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=225), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoa',
    sa.Column('cpf', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=225), nullable=False),
    sa.Column('nascimento', sa.DateTime(), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidade.id'], ),
    sa.PrimaryKeyConstraint('cpf')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    op.drop_table('pessoa')
    op.drop_table('disciplina')
    op.drop_table('cidade')
    op.drop_table('uf')
    op.drop_table('curso')
    # ### end Alembic commands ###
